import type { ModuleConfig } from "./types";

export const CORE_MODULES: ModuleConfig[] = [
  {
    table: "branches",
    name: "Branches",
    icon: "ri-building-2-line",
    select: "id, name, location, manager_name, status, deleted_at, deleted_by",
    label: (r) => r.name,
    detail: (r) => `Branch · ${r.location} · ${r.status}`,
    applyBranchFilter: (q, b) => q.eq("id", b),
  },
  {
    table: "disciplinary_records",
    name: "Disciplinary",
    icon: "ri-alert-line",
    select: "id, title, severity, deleted_at, deleted_by, created_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `Disciplinary · severity ${r.severity}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "documents",
    name: "Documents",
    icon: "ri-folder-line",
    select: "id, title, category, file_url, deleted_at, deleted_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `Document · ${r.category}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "announcements",
    name: "Announcements",
    icon: "ri-megaphone-line",
    select: "id, title, category, deleted_at, deleted_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `Announcement · ${r.category}`,
    applyBranchFilter: (q, b) => q.or(`branch_id.eq.${b},branch_id.is.null`),
  },
  {
    table: "tasks",
    name: "Tasks",
    icon: "ri-checkbox-multiple-line",
    select: "id, title, priority, deleted_at, deleted_by, employees!inner(branch_id)",
    label: (r) => r.title,
    detail: (r) => `Task · ${r.priority}`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "it_assets",
    name: "IT Assets",
    icon: "ri-computer-line",
    select: "id, name, asset_tag, deleted_at, deleted_by, branch_id",
    label: (r) => r.name,
    detail: (r) => `IT Asset · ${r.asset_tag || "no tag"}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "it_tickets",
    name: "IT Tickets",
    icon: "ri-ticket-line",
    select: "id, title, category, deleted_at, deleted_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `IT Ticket · ${r.category}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "expense_records",
    name: "Expenses",
    icon: "ri-bank-line",
    select: "id, category, amount, description, deleted_at, deleted_by, branch_id",
    label: (r) => `${r.category} — $${Number(r.amount || 0).toLocaleString()}`,
    detail: (r) => r.description || "Expense record",
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "job_postings",
    name: "Job Postings",
    icon: "ri-briefcase-line",
    select: "id, title, department, deleted_at, deleted_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `Job Posting · ${r.department || "—"}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "candidates",
    name: "Candidates",
    icon: "ri-user-search-line",
    select: "id, full_name, stage, job_postings!inner(title, branch_id), deleted_at, deleted_by",
    label: (r) => r.full_name,
    detail: (r) => `Candidate · ${r.job_postings?.title || "—"} · ${r.stage}`,
    applyBranchFilter: (q, b) => q.eq("job_postings.branch_id", b),
  },
  {
    table: "interviews",
    name: "Interviews",
    icon: "ri-calendar-event-line",
    select: "id, scheduled_at, deleted_at, deleted_by, candidates!inner(job_postings!inner(branch_id))",
    label: (r) => `Interview · ${r.scheduled_at ? new Date(r.scheduled_at).toLocaleString() : "—"}`,
    detail: (r) => "Scheduled interview",
    applyBranchFilter: (q, b) => q.eq("candidates.job_postings.branch_id", b),
  },
];
