import type { ModuleConfig } from "./types";

export const EXTENDED_MODULES: ModuleConfig[] = [
  {
    table: "training_courses",
    name: "Training Courses",
    icon: "ri-graduation-cap-line",
    select: "id, title, category, deleted_at, deleted_by, branch_id",
    label: (r) => r.title,
    detail: (r) => `Course · ${r.category}`,
    applyBranchFilter: (q, b) => q.or(`branch_id.eq.${b},branch_id.is.null`),
  },
  {
    table: "training_enrollments",
    name: "Training Enrollments",
    icon: "ri-bookmark-line",
    select: "id, status, training_courses!inner(title, branch_id), deleted_at, deleted_by",
    label: (r) => r.training_courses?.title || `Enrollment #${r.id}`,
    detail: (r) => `Enrollment · ${r.status}`,
    applyBranchFilter: (q, b) => q.or(`training_courses.branch_id.eq.${b},training_courses.branch_id.is.null`),
  },
  {
    table: "room_bookings",
    name: "Room Bookings",
    icon: "ri-door-open-line",
    select: "id, title, date, deleted_at, deleted_by",
    label: (r) => r.title,
    detail: (r) => `Room Booking · ${r.date}`,
  },
  {
    table: "onboarding_requests",
    name: "Onboarding Requests",
    icon: "ri-user-star-line",
    select: "id, stage, status, deleted_at, deleted_by, employees!inner(first_name, last_name, branch_id)",
    label: (r) => `${r.employees?.first_name || ""} ${r.employees?.last_name || ""}`.trim() || "Candidate",
    detail: (r) => `Onboarding · stage ${r.stage}`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "onboarding_checklist_tasks",
    name: "Onboarding Checklist",
    icon: "ri-task-line",
    select: "id, task_name, category, deleted_at, deleted_by",
    label: (r) => r.task_name,
    detail: (r) => `Checklist Task · ${r.category}`,
  },
  {
    table: "employees",
    name: "Employees",
    icon: "ri-team-line",
    select: "id, first_name, last_name, email, role, department, deleted_at, deleted_by, branch_id",
    label: (r) => `${r.first_name} ${r.last_name}`,
    detail: (r) => `${r.role || "Employee"} · ${r.department || "No department"} · ${r.email}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "onboarding_documents",
    name: "Onboarding Documents",
    icon: "ri-file-text-line",
    select: "id, document_name, document_type, deleted_at, deleted_by, employees!inner(branch_id)",
    label: (r) => r.document_name,
    detail: (r) => `Onboarding document · ${r.document_type || "General"}`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "attendance_records",
    name: "Attendance Records",
    icon: "ri-calendar-check-line",
    select: "id, date, status, deleted_at, deleted_by, employees!inner(first_name, last_name, branch_id)",
    label: (r) => `${r.employees?.first_name || "Unknown"} ${r.employees?.last_name || "employee"} · ${r.date}`,
    detail: (r) => `Attendance · ${r.status}`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "user_role_assignments",
    name: "User Roles & Accounts",
    icon: "ri-user-settings-line",
    select: "id, email, display_name, deleted_at, deleted_by, app_roles(name)",
    label: (r) => r.display_name ? `${r.display_name} (${r.email})` : r.email,
    detail: (r) => `User Account · ${r.app_roles?.name || "No role"}`,
  },
  {
    table: "shifts",
    name: "Shifts",
    icon: "ri-time-line",
    select: "id, name, department, shift_date, start_time, end_time, deleted_at, deleted_by, branch_id",
    label: (r) => `${r.name} (${r.shift_date})`,
    detail: (r) => `Shift · ${r.start_time} - ${r.end_time} · ${r.department}`,
    applyBranchFilter: (q, b) => q.eq("branch_id", b),
  },
  {
    table: "shift_assignments",
    name: "Shift Assignments",
    icon: "ri-calendar-schedule-line",
    select: "id, status, employee:employees!inner(first_name, last_name, branch_id), deleted_at, deleted_by",
    label: (r) => `${r.employee?.first_name || "?"} ${r.employee?.last_name || "?"}`,
    detail: (r) => `Shift Assignment · ${r.status}`,
    applyBranchFilter: (q, b) => q.eq("employee.branch_id", b),
  },
  {
    table: "leave_requests",
    name: "Leave Requests",
    icon: "ri-calendar-event-line",
    select: "id, leave_type, start_date, end_date, days, deleted_at, deleted_by, employees!inner(first_name, last_name, branch_id)",
    label: (r) => `${r.employees?.first_name || ""} ${r.employees?.last_name || ""} (${r.leave_type})`,
    detail: (r) => `Leave · ${r.start_date} to ${r.end_date} (${r.days} days)`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "work_logs",
    name: "Daily Work Logs",
    icon: "ri-file-list-3-line",
    select: "id, activity, log_date, deleted_at, deleted_by, employees!inner(branch_id)",
    label: (r) => r.activity,
    detail: (r) => `Work Log · ${r.log_date}`,
    applyBranchFilter: (q, b) => q.eq("employees.branch_id", b),
  },
  {
    table: "password_reset_requests",
    name: "Password Resets",
    icon: "ri-lock-password-line",
    select: "id, email, status, requested_at, deleted_at, deleted_by",
    label: (r) => r.email,
    detail: (r) => `Password Reset · ${r.status} · requested ${r.requested_at ? new Date(r.requested_at).toLocaleString() : "—"}`,
  },
];
