export const PERMISSION_COLUMNS = [
  { key: "employees", label: "Employees" },
  { key: "payroll", label: "Payroll" },
  { key: "finance", label: "Finance" },
  { key: "settings", label: "Settings" },
];

export const SETTINGS_SECTIONS = [
  { key: "appearance", label: "Appearance", icon: "ri-palette-line" },
  { key: "notifications", label: "Notifications", icon: "ri-notification-3-line" },
  { key: "otp_rate_limit", label: "OTP Limits", icon: "ri-shield-keyhole-line" },
  { key: "password_reset_limit", label: "Reset Password", icon: "ri-key-2-line" },
  { key: "email_smtp", label: "Email (SMTP)", icon: "ri-mail-settings-line" },
  { key: "permissions", label: "Permissions", icon: "ri-lock-2-line" },
  { key: "branches", label: "Organization", icon: "ri-building-line" },
  { key: "integrations", label: "Integrations", icon: "ri-apps-2-line" },
  { key: "cache_performance", label: "Global Cache", icon: "ri-flashlight-line" },
];

export const keyLabels: Record<string, string> = {
  company_name: "Company Name",
  default_currency: "Default Currency",
  timezone: "Timezone",
  fiscal_year_start: "Fiscal Year Start",
  week_start_day: "Week Start Day",
  work_start_time: "Work Start Time",
  work_end_time: "Work End Time",
  working_days: "Working Days",
  break_start_time: "Break Start Time",
  break_end_time: "Break End Time",
  saturday_start_time: "Saturday Start Time",
  saturday_end_time: "Saturday End Time",
  late_grace_minutes: "Late Grace Period (Mins)",
  early_leave_grace_minutes: "Early Checkout Grace Period (Mins)",
  morning_check_in_start: "Morning Check-In Window Start",
  morning_check_in_end: "Morning Check-In Window End",
  morning_check_out_start: "Morning Check-Out Window Start",
  morning_check_out_end: "Morning Check-Out Window End",
  afternoon_check_in_start: "Afternoon Check-In Window Start",
  afternoon_check_in_end: "Afternoon Check-In Window End",
  afternoon_check_out_start: "Afternoon Check-Out Window Start",
  afternoon_check_out_end: "Afternoon Check-Out Window End",
  checkout_reminder_minutes: "Checkout Reminder Window",
  default_work_hours: "Default Work Hours / Week",
  overtime_threshold: "Overtime Threshold (hours)",
  leave_approval_required: "Leave Approval Required",
  auto_payroll_reminder: "Auto Payroll Reminder",
  attendance_notify_scope:
    "Attendance Check-in/Check-out Notification Scope",
  telegram_notify_enabled: "Telegram Group Notifications",
  telegram_notifications_chat_id: "Action Notifications Telegram Group ID",
  telegram_otp_chat_id: "OTP Telegram Group ID",
  telegram_otp_enabled: "Phone Number OTP via Telegram Bot",
  biometric_offline_alert_enabled: "Biometric Device Offline Alerts",
  biometric_offline_threshold_minutes: "Biometric Device Offline Threshold (Minutes)",
  official_form_logo: "Official Documents Form Logo",
  company_khmer_name: "Company Khmer Name",
  company_english_name: "Company English Name",
  // SMTP email settings
  smtp_host: "SMTP Host",
  smtp_port: "SMTP Port",
  smtp_secure: "SMTP Secure (SSL/TLS)",
  smtp_user: "SMTP Username",
  smtp_pass: "SMTP Password",
  smtp_from_name: "Sender Name",
  smtp_from_email: "Sender Email",
  smtp_send_on_signup: "Send Sign-up Code by Email",
  smtp_send_on_invite: "Send User Invitation by Email",
  // OTP rate limit settings
  otp_code_lifetime_minutes: "OTP Code Lifetime (minutes)",
  otp_codes_per_hour: "OTP Codes Per Hour",
  otp_wrong_tries_per_code: "OTP Wrong Tries Per Code",
  otp_resend_wait_seconds: "OTP Resend Wait (seconds)",
  // Password reset rate limit settings
  password_reset_lifetime_minutes: "Password Reset Link Lifetime (minutes)",
  password_reset_per_hour: "Max Password Reset Requests Per Hour",
  password_reset_resend_wait_seconds: "Password Reset Resend Wait (seconds)",
  password_reset_max_daily: "Max Daily Password Reset Requests",
};

export const notificationKeys = [
  { key: "notification_email_new_leave", label: "New leave request", channel: "email" },
  { key: "notification_push_new_leave", label: "New leave request", channel: "push" },
  { key: "notification_email_payroll", label: "Payroll processed", channel: "email" },
  { key: "notification_push_payroll", label: "Payroll processed", channel: "push" },
  { key: "notification_email_onboarding", label: "Onboarding milestone", channel: "email" },
  { key: "notification_push_onboarding", label: "Onboarding milestone", channel: "push" },
  { key: "notification_email_security", label: "Security alert", channel: "email" },
  { key: "notification_push_security", label: "Security alert", channel: "push" },
  { key: "notification_email_weekly", label: "Weekly summary", channel: "email" },
  { key: "notification_push_weekly", label: "Weekly summary", channel: "push" },
];

export const EVENT_LABELS = [
  "New leave request",
  "Payroll processed",
  "Onboarding milestone",
  "Security alert",
  "Weekly summary",
];

export const ATTENDANCE_SCHEDULE_KEYS = [
  "work_start_time",
  "morning_check_in_start",
  "morning_check_in_end",
  "late_grace_minutes",
  "break_start_time",
  "morning_check_out_start",
  "morning_check_out_end",
  "early_leave_grace_minutes",
  "break_end_time",
  "afternoon_check_in_start",
  "afternoon_check_in_end",
  "work_end_time",
  "afternoon_check_out_start",
  "afternoon_check_out_end",
  "working_days",
  "saturday_start_time",
  "saturday_end_time",
  "checkout_reminder_minutes",
];

export const timezoneOptions = [
  "Asia/Phnom_Penh",
  "Asia/Bangkok",
  "Asia/Ho_Chi_Minh",
  "Asia/Vientiane",
  "Asia/Singapore",
  "Asia/Kuala_Lumpur",
  "Asia/Jakarta",
  "Asia/Manila",
  "Asia/Kolkata",
  "Asia/Dubai",
  "Asia/Tokyo",
  "Asia/Shanghai",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "America/New_York",
  "America/Chicago",
  "America/Los_Angeles",
  "America/Denver",
  "America/Phoenix",
  "America/Anchorage",
  "Pacific/Honolulu",
  "Australia/Sydney",
  "UTC",
];

export const currencyOptions = [
  "USD",
  "EUR",
  "GBP",
  "CAD",
  "AUD",
  "JPY",
  "CNY",
  "CHF",
];

export const INTEGRATIONS = [
  { name: "Slack", connected: true, desc: "Send HR notifications to Slack channels", lastSync: "2 hours ago" },
  { name: "Google Workspace", connected: true, desc: "Sync employee accounts and calendars", lastSync: "1 day ago" },
  { name: "Zoom", connected: false, desc: "Schedule interviews and meetings", lastSync: "Never" },
  { name: "QuickBooks", connected: true, desc: "Sync payroll and financial data", lastSync: "3 hours ago" },
  { name: "Stripe", connected: false, desc: "Process reimbursements and bonuses", lastSync: "Never" },
];
