export const actionLabels: Record<string, string> = {
  message_sent: "Sent a message",
  channel_joined: "Joined a channel",
  file_shared: "Shared a file",
  huddle_started: "Started a huddle",
  pull_request: "Opened a pull request",
  code_review: "Reviewed code",
  commit_pushed: "Pushed a commit",
  branch_created: "Created a branch",
  issue_created: "Created an issue",
  prototype_edited: "Edited a prototype",
  design_viewed: "Viewed a design",
  comment_added: "Added a comment",
  frame_created: "Created a frame",
  meeting_hosted: "Hosted a meeting",
  meeting_joined: "Joined a meeting",
  issue_updated: "Updated an issue",
  sprint_planned: "Planned a sprint",
  ticket_created: "Created a ticket",
  ticket_resolved: "Resolved a ticket",
  lead_updated: "Updated a lead",
  report_viewed: "Viewed a report",
  instance_launched: "Launched an instance",
  deploy_triggered: "Triggered a deploy",
};
