export const categoryColors: Record<string, string> = {
  Communication: "bg-emerald-50 text-emerald-700",
  Engineering: "bg-sky-50 text-sky-700",
  Design: "bg-rose-50 text-rose-700",
  Productivity: "bg-amber-50 text-amber-700",
  Sales: "bg-violet-50 text-violet-700",
  HR: "bg-teal-50 text-teal-700",
  Security: "bg-red-50 text-red-700",
};

export const actionLabels: Record<string, string> = {
  message_sent: "sent a message",
  channel_joined: "joined a channel",
  file_shared: "shared a file",
  huddle_started: "started a huddle",
  pull_request: "opened a PR",
  code_review: "reviewed code",
  commit_pushed: "pushed a commit",
  branch_created: "created a branch",
  issue_created: "created an issue",
  prototype_edited: "edited a prototype",
  design_viewed: "viewed a design",
  comment_added: "added a comment",
  frame_created: "created a frame",
  meeting_hosted: "hosted a meeting",
  meeting_joined: "joined a meeting",
  issue_updated: "updated an issue",
  sprint_planned: "planned a sprint",
  ticket_created: "created a ticket",
  ticket_resolved: "resolved a ticket",
  lead_updated: "updated a lead",
  report_viewed: "viewed a report",
  instance_launched: "launched an instance",
  deploy_triggered: "triggered a deploy",
};
