import type { StageConfigItem, NewJobFormState, NewCandidateFormState, NewInterviewFormState, NewHiringRequestFormState } from "./types";

export const STAGE_CONFIG: Record<string, StageConfigItem> = {
  applied: {
    label: "CV Received",
    bg: "bg-slate-100",
    text: "text-slate-700",
    border: "border-slate-200",
    icon: "ri-file-user-line",
    hex: "#64748B",
  },
  cv_received: {
    label: "CV Received",
    bg: "bg-slate-100",
    text: "text-slate-700",
    border: "border-slate-200",
    icon: "ri-file-user-line",
    hex: "#64748B",
  },
  screening: {
    label: "Screening",
    bg: "bg-amber-50",
    text: "text-amber-700",
    border: "border-amber-200",
    icon: "ri-search-eye-line",
    hex: "#D97706",
  },
  shortlisted: {
    label: "Shortlisted",
    bg: "bg-orange-50",
    text: "text-orange-700",
    border: "border-orange-200",
    icon: "ri-user-star-line",
    hex: "#EA580C",
  },
  hr_interview: {
    label: "HR Interview",
    bg: "bg-sky-50",
    text: "text-sky-700",
    border: "border-sky-200",
    icon: "ri-user-voice-line",
    hex: "#0284C7",
  },
  interview: {
    label: "HR Interview",
    bg: "bg-sky-50",
    text: "text-sky-700",
    border: "border-sky-200",
    icon: "ri-user-voice-line",
    hex: "#0284C7",
  },
  hiring_manager_interview: {
    label: "Hiring Manager Interview",
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    icon: "ri-briefcase-3-line",
    hex: "#2563EB",
  },
  final_interview: {
    label: "Final Interview",
    bg: "bg-indigo-50",
    text: "text-indigo-700",
    border: "border-indigo-200",
    icon: "ri-award-line",
    hex: "#4F46E5",
  },
  selected: {
    label: "Selected",
    bg: "bg-violet-50",
    text: "text-violet-700",
    border: "border-violet-200",
    icon: "ri-checkbox-circle-line",
    hex: "#7C3AED",
  },
  candidate_approval: {
    label: "Candidate Approval",
    bg: "bg-[#253C7D]/10",
    text: "text-[#253C7D]",
    border: "border-[#253C7D]/20",
    icon: "ri-file-check-line",
    hex: "#253C7D",
  },
  salary_negotiation: {
    label: "Salary Negotiation",
    bg: "bg-yellow-50",
    text: "text-yellow-800",
    border: "border-yellow-200",
    icon: "ri-money-dollar-circle-line",
    hex: "#CA8A04",
  },
  offer: {
    label: "Offer",
    bg: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    icon: "ri-mail-send-line",
    hex: "#9333EA",
  },
  accepted: {
    label: "Accepted",
    bg: "bg-teal-50",
    text: "text-teal-700",
    border: "border-teal-200",
    icon: "ri-thumb-up-line",
    hex: "#0D9488",
  },
  documents: {
    label: "Documents",
    bg: "bg-cyan-50",
    text: "text-cyan-700",
    border: "border-cyan-200",
    icon: "ri-file-copy-2-line",
    hex: "#0891B2",
  },
  contract: {
    label: "Contract",
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    border: "border-emerald-200",
    icon: "ri-file-text-line",
    hex: "#059669",
  },
  hired: {
    label: "Hired",
    bg: "bg-emerald-100",
    text: "text-emerald-800",
    border: "border-emerald-300",
    icon: "ri-checkbox-circle-fill",
    hex: "#10B981",
  },
  rejected: {
    label: "Rejected",
    bg: "bg-rose-50",
    text: "text-rose-700",
    border: "border-rose-200",
    icon: "ri-close-circle-line",
    hex: "#F43F5E",
  },
};

export const PIPELINE_STAGES = [
  "cv_received",
  "screening",
  "shortlisted",
  "hr_interview",
  "hiring_manager_interview",
  "final_interview",
  "selected",
  "candidate_approval",
  "salary_negotiation",
  "offer",
  "accepted",
  "documents",
  "contract",
  "hired",
  "rejected",
];

export const STAGE_TIMELINE_ORDER = [
  "cv_received",
  "screening",
  "shortlisted",
  "hr_interview",
  "hiring_manager_interview",
  "final_interview",
  "selected",
  "candidate_approval",
  "salary_negotiation",
  "offer",
  "accepted",
  "documents",
  "contract",
  "hired",
];

export const DEFAULT_DEPARTMENTS = [
  "Operations",
  "Finance",
  "HR",
  "Marketing",
  "Sales",
  "Engineering",
  "IT",
  "Legal",
  "Executive",
  "Customer Service",
  "Other",
];

export const INITIAL_JOB_FORM: NewJobFormState = {
  title: "",
  department: "",
  branch_id: "",
  description: "",
  location: "On-site",
  salary_min: "",
  salary_max: "",
  type: "full-time",
  closing_date: "",
};

export const INITIAL_HIRING_REQUEST_FORM: NewHiringRequestFormState = {
  title: "",
  department: "",
  division: "",
  company: "UNI",
  business_unit: "",
  branch_id: "",
  position_type: "new",
  replacement_for_id: "",
  replacement_for_name: "",
  location: "",
  target_joining_date: "",
  job_description: "",
  hiring_manager_id: "",
  hiring_manager_name: "",
  headcount: 1,
  employment_type: "full-time",
  salary_min: "",
  salary_max: "",
  justification: "",
  urgency: "medium",
};

export const CANDIDATE_SOURCES = [
  "LinkedIn",
  "Telegram",
  "Employee Referral",
  "Walk-in",
  "Direct Website",
  "Job Board",
  "Agency",
  "Other",
];

export const NOTICE_PERIOD_OPTIONS = [
  "Immediate",
  "1 Week",
  "2 Weeks",
  "1 Month",
  "2 Months",
  "3 Months",
  "Negotiable",
];

export const INITIAL_CANDIDATE_FORM: NewCandidateFormState = {
  full_name: "",
  email: "",
  phone: "",
  location: "",
  education: "",
  work_experience: "",
  skills: "",
  languages: "",
  expected_salary: "",
  notice_period: "1 Month",
  assigned_recruiter_id: "",
  tags: "",
  job_posting_id: "",
  source: "LinkedIn",
  notes: "",
};

export const INITIAL_INTERVIEW_FORM: NewInterviewFormState = {
  candidate_id: "",
  scheduled_at: "",
  duration_minutes: "60",
  type: "video",
  notes: "",
  interviewer_id: "",
  interviewer_name: "",
};

