import type { MovementType, MovementTypeConfig } from "./types";

export const MOVEMENT_TYPES: Record<MovementType, MovementTypeConfig> = {
  probation: {
    type: "probation",
    label: "Probation",
    shortLabel: "Probation",
    icon: "ri-time-line",
    badgeBg: "bg-amber-50 dark:bg-amber-950/30",
    badgeText: "text-amber-700 dark:text-amber-400",
    badgeBorder: "border-amber-200 dark:border-amber-800",
    accentColor: "#d97706",
    description: "Assign or extend probation period with specific appraisal milestones.",
  },
  pass_probation: {
    type: "pass_probation",
    label: "Pass Probation",
    shortLabel: "Passed",
    icon: "ri-checkbox-circle-line",
    badgeBg: "bg-emerald-50 dark:bg-emerald-950/30",
    badgeText: "text-emerald-700 dark:text-emerald-400",
    badgeBorder: "border-emerald-200 dark:border-emerald-800",
    accentColor: "#059669",
    description: "Official confirmation to permanent employment following successful performance evaluation.",
  },
  transfer: {
    type: "transfer",
    label: "Transfer",
    shortLabel: "Transfer",
    icon: "ri-arrow-left-right-line",
    badgeBg: "bg-sky-50 dark:bg-sky-950/30",
    badgeText: "text-sky-700 dark:text-sky-400",
    badgeBorder: "border-sky-200 dark:border-sky-800",
    accentColor: "#0284c7",
    description: "Relocate employee across branches, operating sites, or departments.",
  },
  promote: {
    type: "promote",
    label: "Promote",
    shortLabel: "Promote",
    icon: "ri-arrow-up-circle-line",
    badgeBg: "bg-purple-50 dark:bg-purple-950/30",
    badgeText: "text-purple-700 dark:text-purple-400",
    badgeBorder: "border-purple-200 dark:border-purple-800",
    accentColor: "#7c3aed",
    description: "Upward advancement in title, organizational level, or supervisory scope.",
  },
  demote: {
    type: "demote",
    label: "Demote",
    shortLabel: "Demote",
    icon: "ri-arrow-down-circle-line",
    badgeBg: "bg-rose-50 dark:bg-rose-950/30",
    badgeText: "text-rose-700 dark:text-rose-400",
    badgeBorder: "border-rose-200 dark:border-rose-800",
    accentColor: "#e11d48",
    description: "Reclassification to a lower role, level, or restructuring band.",
  },
  salary_adjustment: {
    type: "salary_adjustment",
    label: "Salary Adjustment",
    shortLabel: "Salary Adj.",
    icon: "ri-money-dollar-circle-line",
    badgeBg: "bg-teal-50 dark:bg-teal-950/30",
    badgeText: "text-teal-700 dark:text-teal-400",
    badgeBorder: "border-teal-200 dark:border-teal-800",
    accentColor: "#0d9488",
    description: "Base compensation increase, merit raise, market adjustment, or allowance revision.",
  },
  change_contract: {
    type: "change_contract",
    label: "Change Contract",
    shortLabel: "Contract",
    icon: "ri-file-text-line",
    badgeBg: "bg-indigo-50 dark:bg-indigo-950/30",
    badgeText: "text-indigo-700 dark:text-indigo-400",
    badgeBorder: "border-indigo-200 dark:border-indigo-800",
    accentColor: "#4f46e5",
    description: "Contract renewal, converting Fixed-Duration (FDC) to Undetermined (UDC) or term updates.",
  },
};

export const CONTRACT_TYPES = [
  "Fixed Duration Contract (FDC)",
  "Undetermined Duration Contract (UDC)",
  "Probation Contract",
  "Internship Agreement",
  "Consultancy / Independent Contractor",
  "Part-Time Contract",
];

export const SALARY_ADJUSTMENT_REASONS = [
  "Annual Merit Increment",
  "Promotion Increment",
  "Cost of Living / Inflation Adjustment",
  "Market Calibration",
  "Probation Completion Increment",
  "Role Restructure",
  "Performance Bonus Integration",
];
