export const COLUMN_KEY_MAP: Record<string, string> = {
  "Employee": "employee",
  "Department": "department",
  "Type": "leave_type",
  "Start Date": "start_date",
  "End Date": "end_date",
  "Days": "days",
  "Status": "status",
  "Month": "month",
  "Base Salary": "base_salary",
  "Bonus": "bonus",
  "Deductions": "deductions",
  "Net Pay": "net_pay",
  "Branch": "branch",
  "Total Headcount": "employee_count",
  "Active": "active",
  "Onboarding": "onboarding",
  "Deleted / Inactive": "deleted_count",
  "Description": "description",
  "Category": "category",
  "Amount": "amount",
  "Submitted By": "submitted_by",
  "Date": "date",
  "Candidate": "candidate",
  "Position": "position",
  "Stage": "stage",
  "Applied Date": "applied_date",
  "Time": "time",
  "Activity": "activity",
  "Notes": "notes",
  "Room": "room_name",
  "Title": "title",
  "Booked By": "employee",
  "Attendees": "attendees",
  "Role": "role",
  "Verified Docs": "verified_docs",
  "Requested By": "requested_by",
  "Started Date": "started_date",
  "Task Name": "task_name",
  "Priority": "priority",
  "Assigned To": "assigned_to",
  "Due Date": "due_date",
  "Verified By": "completed_by",
  "Verified Date & Time": "verified_at",
  "Verified At": "verified_at",
  "Completed Date": "completed_at",
  "Shift Date": "shift_date",
  "Shift Name": "shift_name",
  "Hours": "hours",
  "Capacity": "capacity",
  "Staffing": "staffing",
  "Deleted By": "deleted_by",
  "Deleted Date & Time": "deleted_at_formatted",
  "Deleted At": "deleted_at_formatted",
  "Check In": "clock_in",
  "Check Out": "clock_out",
  "Late (Min)": "late_minutes",
  "Days Logged": "days_logged",
  "Present": "present",
  "Late": "late",
  "Absent": "absent",
  "Remote": "remote",
  "Total Hours": "total_hours",
  "Late Minutes": "late_minutes",
  "Attendance Rate (%)": "attendance_rate",
  "Last Logged": "last_logged",
};
