import type { Holiday } from "./holidayTypes";

// Built-in Cambodia Labor Law Public Holidays (Prakas / Official Calendar)
// Provides instant offline fallback and baseline data
export const CAMBODIA_HOLIDAYS_FALLBACK: Record<number, Omit<Holiday, "id" | "created_at">[]> = {
  2025: [
    { date: "2025-01-01", name: "New Year's Day", local_name: "ទិវាបុណ្យចូលឆ្នាំសកល", year: 2025, is_paid: true },
    { date: "2025-01-07", name: "Victory over Genocide Day", local_name: "ទិវាជ័យជម្នះលើរបបប្រល័យពូជសាសន៍", year: 2025, is_paid: true },
    { date: "2025-03-08", name: "International Women's Day", local_name: "ទិវានារីអន្តរជាតិ", year: 2025, is_paid: true },
    { date: "2025-04-14", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2025, is_paid: true },
    { date: "2025-04-15", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2025, is_paid: true },
    { date: "2025-04-16", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2025, is_paid: true },
    { date: "2025-05-01", name: "Labour Day", local_name: "ទិវាពលកម្មអន្តរជាតិ", year: 2025, is_paid: true },
    { date: "2025-05-11", name: "Visak Bochea Day", local_name: "ពិធីបុណ្យវិសាខបូជា", year: 2025, is_paid: true },
    { date: "2025-05-14", name: "King Sihamoni's Birthday", local_name: "ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម ព្រះករុណា នរោត្តម សីហមុនី", year: 2025, is_paid: true },
    { date: "2025-05-15", name: "Royal Ploughing Ceremony", local_name: "ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល", year: 2025, is_paid: true },
    { date: "2025-06-18", name: "Queen Mother's Birthday", local_name: "ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម សម្តេចព្រះមហាក្សត្រី នរោត្តម មុនិនាថ សីហនុ", year: 2025, is_paid: true },
    { date: "2025-09-21", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2025, is_paid: true },
    { date: "2025-09-22", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2025, is_paid: true },
    { date: "2025-09-23", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2025, is_paid: true },
    { date: "2025-09-24", name: "Constitution Day", local_name: "ទិវាប្រកាសរដ្ឋធម្មនុញ្ញ", year: 2025, is_paid: true },
    { date: "2025-10-15", name: "Commemoration Day of the King's Father", local_name: "ព្រះរាជពិធីគោរពព្រះវិញ្ញាណក្ខន្ធព្រះករុណាព្រះបាទសម្ដេចព្រះ នរោត្ដម សីហនុ", year: 2025, is_paid: true },
    { date: "2025-10-29", name: "Coronation Day of King Sihamoni", local_name: "ព្រះរាជពិធីគ្រងព្រះបរមរាជសម្បត្តិរបស់ព្រះករុណាព្រះបាទសម្ដេចព្រះបរមនាថ នរោត្ដម សីហមុនី", year: 2025, is_paid: true },
    { date: "2025-11-04", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2025, is_paid: true },
    { date: "2025-11-05", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2025, is_paid: true },
    { date: "2025-11-06", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2025, is_paid: true },
    { date: "2025-11-09", name: "National Independence Day", local_name: "ទិវាបុណ្យឯករាជ្យជាតិ", year: 2025, is_paid: true },
    { date: "2025-12-29", name: "Cambodia Peace Day", local_name: "ទិវាសន្តិភាពនៅកម្ពុជា", year: 2025, is_paid: true },
  ],
  2026: [
    { date: "2026-01-01", name: "New Year's Day", local_name: "ទិវាបុណ្យចូលឆ្នាំសកល", year: 2026, is_paid: true },
    { date: "2026-01-07", name: "Victory over Genocide Day", local_name: "ទិវាជ័យជម្នះលើរបបប្រល័យពូជសាសន៍", year: 2026, is_paid: true },
    { date: "2026-03-08", name: "International Women's Day", local_name: "ទិវានារីអន្តរជាតិ", year: 2026, is_paid: true },
    { date: "2026-04-14", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2026, is_paid: true },
    { date: "2026-04-15", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2026, is_paid: true },
    { date: "2026-04-16", name: "Khmer New Year", local_name: "ពិធីបុណ្យចូលឆ្នាំថ្មី ប្រពៃណីជាតិ", year: 2026, is_paid: true },
    { date: "2026-05-01", name: "Labour Day", local_name: "ទិវាពលកម្មអន្តរជាតិ", year: 2026, is_paid: true },
    { date: "2026-05-05", name: "Royal Ploughing Ceremony", local_name: "ព្រះរាជពិធីច្រត់ព្រះនង្គ័ល", year: 2026, is_paid: true },
    { date: "2026-05-14", name: "King Sihamoni's Birthday", local_name: "ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម ព្រះករុណា នរោត្តម សីហមុនី", year: 2026, is_paid: true },
    { date: "2026-06-18", name: "Queen Mother's Birthday", local_name: "ព្រះរាជពិធីបុណ្យចម្រើនព្រះជន្ម សម្តេចព្រះមហាក្សត្រី នរោត្តម មុនិនាថ សីហនុ", year: 2026, is_paid: true },
    { date: "2026-09-24", name: "Constitution Day", local_name: "ទិវាប្រកាសរដ្ឋធម្មនុញ្ញ", year: 2026, is_paid: true },
    { date: "2026-10-10", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2026, is_paid: true },
    { date: "2026-10-11", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2026, is_paid: true },
    { date: "2026-10-12", name: "Pchum Ben", local_name: "ពិធីបុណ្យភ្ផុំបិណ្ឌ", year: 2026, is_paid: true },
    { date: "2026-10-15", name: "Commemoration Day of the King's Father", local_name: "ព្រះរាជពិធីគោរពព្រះវិញ្ញាណក្ខន្ធព្រះករុណាព្រះបាទសម្ដេចព្រះ នរោត្ដម សីហនុ", year: 2026, is_paid: true },
    { date: "2026-10-29", name: "Coronation Day of King Sihamoni", local_name: "ព្រះរាជពិធីគ្រងព្រះបរមរាជសម្បត្តិរបស់ព្រះករុណាព្រះបាទសម្ដេចព្រះបរមនាថ នរោត្ដម សីហមុនី", year: 2026, is_paid: true },
    { date: "2026-11-09", name: "National Independence Day", local_name: "ទិវាបុណ្យឯករាជ្យជាតិ", year: 2026, is_paid: true },
    { date: "2026-11-23", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2026, is_paid: true },
    { date: "2026-11-24", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2026, is_paid: true },
    { date: "2026-11-25", name: "Water Festival", local_name: "ពិធីបុណ្យអុំទូក បណ្ដែតប្រទីប អកអំបុក និងសំពះព្រះខែ", year: 2026, is_paid: true },
    { date: "2026-12-29", name: "Cambodia Peace Day", local_name: "ទិវាសន្តិភាពនៅកម្ពុជា", year: 2026, is_paid: true },
  ],
};
