-- Migration: Create biometric_device_commands table for queuing ADMS commands to ZKTeco terminals
CREATE TABLE IF NOT EXISTS public.biometric_device_commands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_serial text NOT NULL,
  command text NOT NULL,
  status text NOT NULL DEFAULT 'pending', -- pending, sent, success, failed
  created_at timestamptz DEFAULT now(),
  sent_at timestamptz,
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_biometric_device_commands_device ON public.biometric_device_commands (device_serial, status);

ALTER TABLE public.biometric_device_commands ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow service role full access to biometric_device_commands') THEN
    CREATE POLICY "Allow service role full access to biometric_device_commands" ON public.biometric_device_commands
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated read biometric_device_commands') THEN
    CREATE POLICY "Allow authenticated read biometric_device_commands" ON public.biometric_device_commands
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated insert biometric_device_commands') THEN
    CREATE POLICY "Allow authenticated insert biometric_device_commands" ON public.biometric_device_commands
      FOR INSERT TO authenticated WITH CHECK (true);
  END IF;
END
$$;
