-- Add or update Branch Admin role in app_roles
insert into app_roles (
  name,
  description,
  color,
  is_admin,
  allowed_modules,
  employees_manage,
  self_service_all_employees,
  leave_view_all_employees,
  leave_approve,
  payroll_view_all_employees,
  attendance_view_all_employees,
  performance_view_all_employees,
  disciplinary_view_all_employees,
  leave_view_own_branch,
  attendance_view_own_branch,
  performance_view_own_branch,
  disciplinary_view_own_branch,
  task_view_all_employees,
  task_view_own_branch,
  meeting_rooms_approve,
  attendance_notify
)
values (
  'Branch Admin',
  'Full administrative control and management within assigned branch',
  '#253C7D',
  false,
  array[
    'dashboard',
    'employees',
    'branches',
    'analytics',
    'onboarding',
    'onboarding-checklist',
    'leave',
    'leave-calendar',
    'hire',
    'offboard',
    'org-chart',
    'performance',
    'attendance',
    'training',
    'disciplinary',
    'shifts',
    'payroll',
    'payroll-approval',
    'finance',
    'it-management',
    'benefits',
    'tools',
    'announcements',
    'documents',
    'reports',
    'audit-log',
    'self-service',
    'notifications',
    'unity-apps',
    'meeting-rooms',
    'tasks',
    'settings'
  ],
  true,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true
)
on conflict (name) do update set
  description = excluded.description,
  color = excluded.color,
  allowed_modules = excluded.allowed_modules,
  employees_manage = true,
  leave_approve = true,
  leave_view_own_branch = true,
  attendance_view_own_branch = true,
  performance_view_own_branch = true,
  disciplinary_view_own_branch = true,
  task_view_own_branch = true,
  meeting_rooms_approve = true,
  attendance_notify = true;
