export const ALL_MODULES = [
  { key: "dashboard", label: "Dashboard", icon: "ri-dashboard-line", group: "Core" },
  { key: "employees", label: "Employees", icon: "ri-user-search-line", group: "Core" },
  { key: "branches", label: "Branches", icon: "ri-building-line", group: "Core" },
  { key: "analytics", label: "Analytics", icon: "ri-bar-chart-2-line", group: "Core" },
  { key: "onboarding", label: "Onboarding", icon: "ri-user-add-line", group: "Workforce" },
  { key: "onboarding-checklist", label: "Onboarding Checklist", icon: "ri-task-line", group: "Workforce" },
  { key: "leave", label: "Leave Requests", icon: "ri-calendar-event-line", group: "Workforce" },
  { key: "leave-calendar", label: "Leave Calendar", icon: "ri-calendar-2-line", group: "Workforce" },
  { key: "hire", label: "Recruitment", icon: "ri-briefcase-line", group: "Workforce" },
  { key: "offboard", label: "Offboarding", icon: "ri-user-unfollow-line", group: "Workforce" },
  { key: "org-chart", label: "Org Chart", icon: "ri-organization-chart", group: "Workforce" },
  { key: "performance", label: "Performance", icon: "ri-star-line", group: "Workforce" },
  { key: "attendance", label: "Attendance", icon: "ri-fingerprint-line", group: "Workforce" },
  { key: "training", label: "Training", icon: "ri-graduation-cap-line", group: "Workforce" },
  { key: "disciplinary", label: "Disciplinary", icon: "ri-alert-line", group: "Workforce" },
  { key: "shifts", label: "Shifts", icon: "ri-calendar-schedule-line", group: "Workforce" },
  { key: "meeting-rooms", label: "Meeting Rooms", icon: "ri-door-open-line", group: "Workforce" },
  { key: "tasks", label: "Tasks", icon: "ri-checkbox-multiple-line", group: "Workforce" },
  { key: "payroll", label: "Payroll", icon: "ri-money-dollar-circle-line", group: "Operations" },
  { key: "payroll-approval", label: "Payroll Approval", icon: "ri-file-check-line", group: "Operations" },
  { key: "finance", label: "Finance", icon: "ri-bank-line", group: "Operations" },
  { key: "it-management", label: "IT Management", icon: "ri-computer-line", group: "Operations" },
  { key: "benefits", label: "Benefits", icon: "ri-heart-pulse-line", group: "Operations" },
  { key: "tools", label: "HR Tools", icon: "ri-tools-line", group: "Operations" },
  { key: "announcements", label: "Announcements", icon: "ri-megaphone-line", group: "Operations" },
  { key: "documents", label: "Documents", icon: "ri-folder-line", group: "Operations" },
  { key: "reports", label: "Reports", icon: "ri-file-chart-line", group: "Insights" },
  { key: "audit-log", label: "Audit Log", icon: "ri-shield-check-line", group: "Insights" },
  { key: "self-service", label: "Self-Service", icon: "ri-user-settings-line", group: "Insights" },
  { key: "notifications", label: "Notifications", icon: "ri-notification-3-line", group: "System" },
  { key: "unity-apps", label: "Unity Apps", icon: "ri-apps-line", group: "System" },
  { key: "settings", label: "Settings", icon: "ri-settings-3-line", group: "System" },
] as const;

export const MODULE_GROUPS = ["Core", "Workforce", "Operations", "Insights", "System"] as const;
