export interface CountryDialCode {
  name: string;
  nativeName?: string;
  code: string;
  dialCode: string;
  flag: string;
}

export const COUNTRIES: CountryDialCode[] = [
  { name: "Cambodia", nativeName: "កម្ពុជា", code: "KH", dialCode: "+855", flag: "🇰🇭" },
  { name: "United States", nativeName: "United States", code: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", nativeName: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "Afghanistan", nativeName: "افغانستان", code: "AF", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albania", nativeName: "Shqipëri", code: "AL", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", nativeName: "الجزائر", code: "DZ", dialCode: "+213", flag: "🇩🇿" },
  { name: "American Samoa", nativeName: "American Samoa", code: "AS", dialCode: "+1684", flag: "🇦🇸" },
  { name: "Andorra", nativeName: "Andorra", code: "AD", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", nativeName: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Anguilla", nativeName: "Anguilla", code: "AI", dialCode: "+1264", flag: "🇦🇮" },
  { name: "Argentina", nativeName: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", nativeName: "Հայաստան", code: "AM", dialCode: "+374", flag: "🇦🇲" },
  { name: "Aruba", nativeName: "Aruba", code: "AW", dialCode: "+297", flag: "🇦🇼" },
  { name: "Australia", nativeName: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Austria", nativeName: "Österreich", code: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", nativeName: "Azərbaycan", code: "AZ", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", nativeName: "Bahamas", code: "BS", dialCode: "+1242", flag: "🇧🇸" },
  { name: "Bahrain", nativeName: "البحرين", code: "BH", dialCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", nativeName: "বাংলাদেশ", code: "BD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Barbados", nativeName: "Barbados", code: "BB", dialCode: "+1246", flag: "🇧🇧" },
  { name: "Belarus", nativeName: "Беларусь", code: "BY", dialCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", nativeName: "België", code: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Belize", nativeName: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿" },
  { name: "Benin", nativeName: "Bénin", code: "BJ", dialCode: "+229", flag: "🇧🇯" },
  { name: "Bermuda", nativeName: "Bermuda", code: "BM", dialCode: "+1441", flag: "🇧🇲" },
  { name: "Bhutan", nativeName: "འབྲུག", code: "BT", dialCode: "+975", flag: "🇧🇹" },
  { name: "Bolivia", nativeName: "Bolivia", code: "BO", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", nativeName: "Bosna i Hercegovina", code: "BA", dialCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", nativeName: "Botswana", code: "BW", dialCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", nativeName: "Brasil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Brunei", nativeName: "Brunei", code: "BN", dialCode: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", nativeName: "България", code: "BG", dialCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", nativeName: "Burkina Faso", code: "BF", dialCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", nativeName: "Burundi", code: "BI", dialCode: "+257", flag: "🇧🇮" },
  { name: "Cameroon", nativeName: "Cameroun", code: "CM", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", nativeName: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Cape Verde", nativeName: "Cabo Verde", code: "CV", dialCode: "+238", flag: "🇨🇻" },
  { name: "Cayman Islands", nativeName: "Cayman Islands", code: "KY", dialCode: "+1345", flag: "🇰🇾" },
  { name: "Chile", nativeName: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "China", nativeName: "中国", code: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", nativeName: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Congo", nativeName: "Congo", code: "CG", dialCode: "+242", flag: "🇨🇬" },
  { name: "Costa Rica", nativeName: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷" },
  { name: "Croatia", nativeName: "Hrvatska", code: "HR", dialCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", nativeName: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺" },
  { name: "Cyprus", nativeName: "Κύπρος", code: "CY", dialCode: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", nativeName: "Česká republika", code: "CZ", dialCode: "+420", flag: "🇨🇿" },
  { name: "Denmark", nativeName: "Danmark", code: "DK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Dominican Republic", nativeName: "República Dominicana", code: "DO", dialCode: "+1809", flag: "🇩🇴" },
  { name: "Ecuador", nativeName: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", nativeName: "مصر", code: "EG", dialCode: "+20", flag: "🇪🇬" },
  { name: "El Salvador", nativeName: "El Salvador", code: "SV", dialCode: "+503", flag: "🇸🇻" },
  { name: "Estonia", nativeName: "Eesti", code: "EE", dialCode: "+372", flag: "🇪🇪" },
  { name: "Ethiopia", nativeName: "ኢትዮጵያ", code: "ET", dialCode: "+251", flag: "🇪🇹" },
  { name: "Fiji", nativeName: "Fiji", code: "FJ", dialCode: "+679", flag: "🇫🇯" },
  { name: "Finland", nativeName: "Suomi", code: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", nativeName: "France", code: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Georgia", nativeName: "საქართველო", code: "GE", dialCode: "+995", flag: "🇬🇪" },
  { name: "Germany", nativeName: "Deutschland", code: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", nativeName: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭" },
  { name: "Greece", nativeName: "Ελλάδα", code: "GR", dialCode: "+30", flag: "🇬🇷" },
  { name: "Guatemala", nativeName: "Guatemala", code: "GT", dialCode: "+502", flag: "🇬🇹" },
  { name: "Haiti", nativeName: "Haïti", code: "HT", dialCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", nativeName: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳" },
  { name: "Hong Kong", nativeName: "香港", code: "HK", dialCode: "+852", flag: "🇭🇰" },
  { name: "Hungary", nativeName: "Magyarország", code: "HU", dialCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", nativeName: "Ísland", code: "IS", dialCode: "+354", flag: "🇮🇸" },
  { name: "India", nativeName: "भारत", code: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "Indonesia", nativeName: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩" },
  { name: "Iran", nativeName: "ایران", code: "IR", dialCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", nativeName: "العراق", code: "IQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", nativeName: "Éire", code: "IE", dialCode: "+353", flag: "🇮🇪" },
  { name: "Israel", nativeName: "ישראל", code: "IL", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italy", nativeName: "Italia", code: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Jamaica", nativeName: "Jamaica", code: "JM", dialCode: "+1876", flag: "🇯🇲" },
  { name: "Japan", nativeName: "日本", code: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "Jordan", nativeName: "الأردن", code: "JO", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", nativeName: "Қазақстан", code: "KZ", dialCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", nativeName: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪" },
  { name: "Kuwait", nativeName: "الكويت", code: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Laos", nativeName: "ລາວ", code: "LA", dialCode: "+856", flag: "🇱🇦" },
  { name: "Lebanon", nativeName: "لبنان", code: "LB", dialCode: "+961", flag: "🇱🇧" },
  { name: "Luxembourg", nativeName: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺" },
  { name: "Macau", nativeName: "澳門", code: "MO", dialCode: "+853", flag: "🇲🇴" },
  { name: "Malaysia", nativeName: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾" },
  { name: "Maldives", nativeName: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻" },
  { name: "Mexico", nativeName: "México", code: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Monaco", nativeName: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨" },
  { name: "Mongolia", nativeName: "Монгол", code: "MN", dialCode: "+976", flag: "🇲🇳" },
  { name: "Morocco", nativeName: "المغرب", code: "MA", dialCode: "+212", flag: "🇲🇦" },
  { name: "Myanmar", nativeName: "မြန်မာ", code: "MM", dialCode: "+95", flag: "🇲🇲" },
  { name: "Nepal", nativeName: "नेपाल", code: "NP", dialCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", nativeName: "Nederland", code: "NL", dialCode: "+31", flag: "🇳🇱" },
  { name: "New Zealand", nativeName: "New Zealand", code: "NZ", dialCode: "+64", flag: "🇳🇿" },
  { name: "Nigeria", nativeName: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬" },
  { name: "Norway", nativeName: "Norge", code: "NO", dialCode: "+47", flag: "🇳🇴" },
  { name: "Oman", nativeName: "عُمان", code: "OM", dialCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", nativeName: "پاکستان", code: "PK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Panama", nativeName: "Panamá", code: "PA", dialCode: "+507", flag: "🇵🇦" },
  { name: "Paraguay", nativeName: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾" },
  { name: "Peru", nativeName: "Perú", code: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", nativeName: "Pilipinas", code: "PH", dialCode: "+63", flag: "🇵🇭" },
  { name: "Poland", nativeName: "Polska", code: "PL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", nativeName: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", nativeName: "قطر", code: "QA", dialCode: "+974", flag: "🇶🇦" },
  { name: "Romania", nativeName: "România", code: "RO", dialCode: "+40", flag: "🇷🇴" },
  { name: "Russia", nativeName: "Россия", code: "RU", dialCode: "+7", flag: "🇷🇺" },
  { name: "Saudi Arabia", nativeName: "المملكة العربية السعودية", code: "SA", dialCode: "+966", flag: "🇸🇦" },
  { name: "Senegal", nativeName: "Sénégal", code: "SN", dialCode: "+221", flag: "🇸🇳" },
  { name: "Serbia", nativeName: "Србија", code: "RS", dialCode: "+381", flag: "🇷🇸" },
  { name: "Singapore", nativeName: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Slovakia", nativeName: "Slovensko", code: "SK", dialCode: "+421", flag: "🇸🇰" },
  { name: "Slovenia", nativeName: "Slovenija", code: "SI", dialCode: "+386", flag: "🇸🇮" },
  { name: "South Africa", nativeName: "South Africa", code: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { name: "South Korea", nativeName: "대한민국", code: "KR", dialCode: "+82", flag: "🇰🇷" },
  { name: "Spain", nativeName: "España", code: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", nativeName: "ශ්‍රී ලංකාව", code: "LK", dialCode: "+94", flag: "🇱🇰" },
  { name: "Sweden", nativeName: "Sverige", code: "SE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", nativeName: "Schweiz", code: "CH", dialCode: "+41", flag: "🇨🇭" },
  { name: "Taiwan", nativeName: "台灣", code: "TW", dialCode: "+886", flag: "🇹🇼" },
  { name: "Thailand", nativeName: "ไทย", code: "TH", dialCode: "+66", flag: "🇹🇭" },
  { name: "Turkey", nativeName: "Türkiye", code: "TR", dialCode: "+90", flag: "🇹🇷" },
  { name: "Ukraine", nativeName: "Україна", code: "UA", dialCode: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", nativeName: "الإمارات", code: "AE", dialCode: "+971", flag: "🇦🇪" },
  { name: "Uruguay", nativeName: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", nativeName: "Oʻzbekiston", code: "UZ", dialCode: "+998", flag: "🇺🇿" },
  { name: "Vatican City", nativeName: "Vaticano", code: "VA", dialCode: "+379", flag: "🇻🇦" },
  { name: "Venezuela", nativeName: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", nativeName: "Việt Nam", code: "VN", dialCode: "+84", flag: "🇻🇳" },
  { name: "Yemen", nativeName: "اليمن", code: "YE", dialCode: "+967", flag: "🇾🇪" },
  { name: "Zimbabwe", nativeName: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼" },
];
